In [27]:
print('hello')

hello


In [28]:
import numpy as np

In [29]:
a=np.array([[3,8,4],[9,3,5],[11,15,17],[19,31,8]])
a

array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [30]:
b=np.array([[4,8,7],[3,1,5],[6,9,13]])
b

array([[ 4,  8,  7],
       [ 3,  1,  5],
       [ 6,  9, 13]])

In [31]:
b.shape

(3, 3)

In [32]:
c=np.array([[[4,41],[8,81],[7,71]],
            [[3,31],[1,11],[5,51]],
            [[6,61],[9,91],[13,131]]])
c

array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [33]:
# c[1:3:1,1:3:1,0]
c[1:,1:,:1]

array([[[ 1],
        [ 5]],

       [[ 9],
        [13]]])

In [34]:
c.shape

(3, 3, 2)

In [35]:
# b[1][0]
# b[1,0]
b[1,:]

array([3, 1, 5])

In [36]:
# b[0:4:1,2]
# b[0:5,2]
# b[:,2]
b[:,-1]

array([ 7,  5, 13])

In [37]:
b[:,2].shape

(3,)

In [38]:
# b[2:3]
b[2:,-1:]

array([[13]])

In [39]:
m=np.array([[4,8,7],[3,1,5],[6,9,13]])
m

array([[ 4,  8,  7],
       [ 3,  1,  5],
       [ 6,  9, 13]])

In [40]:
m.shape

(3, 3)

In [41]:
m[1:3,1:3]

array([[ 1,  5],
       [ 9, 13]])

In [42]:
m+5 # it is work only in array not in list 

array([[ 9, 13, 12],
       [ 8,  6, 10],
       [11, 14, 18]])

In [43]:
m[1]=[30,40,50]
m
# for changing the value

array([[ 4,  8,  7],
       [30, 40, 50],
       [ 6,  9, 13]])

In [44]:
m[1,:]=[70,80,90]
m

array([[ 4,  8,  7],
       [70, 80, 90],
       [ 6,  9, 13]])

In [45]:
m[:,1]=[1,2,3]
m

array([[ 4,  1,  7],
       [70,  2, 90],
       [ 6,  3, 13]])

In [46]:
m=np.append(m,[[1,1,1]],axis=0) #zero to add row-vise

In [48]:
np.append(m,[[2],[2],[2]],axis=1)


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 3

In [ ]:
np.delete(m,1,axis=0)

array([[ 5,  1,  5],
       [ 6,  3, 13]])

In [ ]:
np.delete(m,-1,axis=1)

array([[ 5,  1],
       [70,  2],
       [ 6,  3]])

In [ ]:
m

array([[ 5,  1,  5],
       [70,  2, 90],
       [ 6,  3, 13]])

In [ ]:
m.shape


(3, 3)

In [ ]:
m.reshape(1,9)

array([[ 5,  1,  5, 70,  2, 90,  6,  3, 13]])

In [ ]:
m

array([[ 5,  1,  5],
       [70,  2, 90],
       [ 6,  3, 13],
       [ 1,  1,  1]])

In [ ]:
m.reshape(2,6)
m.dtype

dtype('int32')

In [ ]:
a1=np.array([3.5,3,7])
a1

array([3.5, 3. , 7. ])

In [ ]:
a1.dtype

dtype('float64')

In [ ]:
a1.astype('uint16')

NameError: name 'a1' is not defined

In [ ]:
m.mean(axis=0)

array([20.5 ,  1.75, 27.25])

In [ ]:
m.std(axis=1)

array([ 1.88561808, 37.66519171,  4.18993503,  0.        ])

<!-- nutshell -->
## we create arrays
1.np.array()
2.np.ones()
3.np.zeroes()
4.np.arange()
5. np.limspace()
6. np.random.randint()