In [1]:
import numpy as np

In [9]:
# np.ones((2,3),dtype=int)
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.linspace(1,10,10,dtype=int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
list(range(1,11,1))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [21]:
np.random.randint(1,6,1)

array([4])

In [17]:
np.random.randint(1,6,[4,3,2])

array([[[4, 5],
        [3, 1],
        [5, 4]],

       [[5, 5],
        [5, 4],
        [3, 1]],

       [[3, 5],
        [2, 5],
        [3, 3]],

       [[1, 2],
        [1, 1],
        [4, 1]]])

In [30]:
np.random.randint(31,6000,[4,3],)

array([[5879, 2017, 3802],
       [5704, 5547, 3320],
       [2894, 2893, 2296],
       [5048, 5563, 1853]])

In [31]:
np.random.seed(54)
np.random.randint(31,6000,[4,3],)

array([[ 929, 3886, 5174],
       [3840, 3423, 2096],
       [5160, 5669, 4744],
       [3350, 4835, 3347]])

In [34]:
np.random.rand(3,4)

array([[0.30787317, 0.17198668, 0.17538453, 0.16382659],
       [0.58501438, 0.47353556, 0.46075695, 0.23515401],
       [0.85621717, 0.47089378, 0.05458343, 0.99325708]])

In [37]:
r=np.loadtxt('somedata.txt',dtype=str)
r

array(['hii', 'this', 'is', 'some', 'data', 'outside', 'from', 'python'],
      dtype='<U7')

In [40]:
r=np.loadtxt('moredata.txt',dtype=int)
r

array([[ 45,  34,  56,  78],
       [ 30, 440,  45,   2]])

In [42]:
p=np.random.rand(3,4)
p

array([[0.94697523, 0.62174152, 0.72878496, 0.87609123],
       [0.9416747 , 0.12094657, 0.88272535, 0.09609818],
       [0.78274871, 0.65746659, 0.88223916, 0.6536079 ]])

In [48]:
np.savetxt('new.txt',p,delimiter=',')