In [2]:
import numpy as np

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [7]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [8]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [11]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [16]:
p=np.random.rand(1)
p


array([0.42149444])

In [17]:
np.random.randn(25)

array([-0.87060057,  1.15304018, -0.71800118,  0.70959451, -2.22890811,
       -0.77391393,  0.11699571,  0.18281362, -0.23036858, -2.32822618,
        0.33462214, -0.21122866, -1.64045591,  1.39092192,  0.94603502,
        1.82391385, -0.2801531 ,  1.26455559, -0.61000332,  0.89093802,
       -1.2907697 , -0.6395575 ,  1.62974684,  0.81731429,  1.01500646])

In [23]:
np.arange(0.01,1.01,0.01).reshape((10,10))

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [24]:
np.arange(0.01,1.01,0.01).reshape((10,10)).sum(axis=0)

array([4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5])

In [6]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [8]:
m=np.array([[12,13,14,15],[17,18,19,20],[22,23,24,25]])
m

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [1]:
# numpy indexing and selection


In [3]:
import numpy as np
np.linspace(1,25,25,dtype=int).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [4]:
np.arange(21,26,1)

array([21, 22, 23, 24, 25])

In [5]:
np.arange(2,13,5).reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [8]:
np.arange(16,26,1).reshape(2,5)

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [12]:
a=np.array([[40,50,60],[80,90,70],[88,99,78]])
np.sum(a)

655

In [13]:
a=np.array([[40,50,60],[80,90,70],[88,99,78]])
np.std(a)

18.437749789059147

In [14]:
np.sum(a,axis=0)

array([208, 239, 208])

##Great Job